// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUHvUUQ5ZKha7amBNf8ewfT5uSGzPIac',
    appId: '1:459683322029:web:bde1d9077a35d5f4350e24',
    messagingSenderId: '459683322029',
    projectId: 'chatfri',
    authDomain: 'chatfri.firebaseapp.com',
    storageBucket: 'chatfri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4lHE6HzayMY1D2_NJf23OpK9Z3pyS_Y',
    appId: '1:459683322029:android:8c806b17140991d2350e24',
    messagingSenderId: '459683322029',
    projectId: 'chatfri',
    storageBucket: 'chatfri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6Tyn1AVDeOB2cN4NeKUA3Jo6Xj3VjUk',
    appId: '1:459683322029:ios:330f54d659b5f2d9350e24',
    messagingSenderId: '459683322029',
    projectId: 'chatfri',
    storageBucket: 'chatfri.appspot.com',
    iosClientId: '459683322029-7nrr8k6i68g83u6qvoed1fr4asjgdlm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.movistar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6Tyn1AVDeOB2cN4NeKUA3Jo6Xj3VjUk',
    appId: '1:459683322029:ios:330f54d659b5f2d9350e24',
    messagingSenderId: '459683322029',
    projectId: 'chatfri',
    storageBucket: 'chatfri.appspot.com',
    iosClientId: '459683322029-7nrr8k6i68g83u6qvoed1fr4asjgdlm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.movistar',
  );
}
