// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxcG_lm7jY9IJ5ElktW0AR2HrlqcUHso',
    appId: '1:481728261427:web:f580c198efe483d73ba246',
    messagingSenderId: '481728261427',
    projectId: 'movi-93562',
    authDomain: 'movi-93562.firebaseapp.com',
    storageBucket: 'movi-93562.appspot.com',
    measurementId: 'G-5EFBNRGHQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgkYoh15D_vaNxQhzyTh4o2vIA5hWmg8',
    appId: '1:481728261427:android:6e7f81de6d35a03a3ba246',
    messagingSenderId: '481728261427',
    projectId: 'movi-93562',
    storageBucket: 'movi-93562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdGOqRHMSfUEYLFH-zpCOSuj0wHhZc_w',
    appId: '1:481728261427:ios:8003a894d5b2d6353ba246',
    messagingSenderId: '481728261427',
    projectId: 'movi-93562',
    storageBucket: 'movi-93562.appspot.com',
    iosClientId: '481728261427-3m7ei6mgsp9t824ftc2e6tdv87gv7gqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.movi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdGOqRHMSfUEYLFH-zpCOSuj0wHhZc_w',
    appId: '1:481728261427:ios:8003a894d5b2d6353ba246',
    messagingSenderId: '481728261427',
    projectId: 'movi-93562',
    storageBucket: 'movi-93562.appspot.com',
    iosClientId: '481728261427-3m7ei6mgsp9t824ftc2e6tdv87gv7gqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.movi',
  );
}
